### ISSUE TITLE
code for OOD Generalization?

### ISSUE THREAD

**Issue by wenlai-lavine** [BierOne/ood_coverage#2]
Hi,

Thanks for the nice work. Do you also plan to upload the code for OOD Generalization?

**Comment by BierOne** [comment]
Hi, thanks for your interest to our work. OOD generalization also employs a similar code to this repository. I will provide more details later.

**Comment by BierOne** [comment]
Hi, thank you for your patience. I have uploaded the source code for NAC-ME in [here](https://github.com/BierOne/ood_coverage/tree/master/domainbed), which is tailored for generalization tasks. Hope you find it helpful!
