### ISSUE TITLE
Availability of Generalization Code?

### ISSUE THREAD

**Issue by emanehabn** [BierOne/ood_coverage#4]
Hi,

Thank you for your excellent work! I was wondering when the generalization code will be available.

Best regards.

**Comment by BierOne** [comment]
Hi! Thank you for your interest in our work. I will organize the generalization code this month and update it soon!

**Comment by emanehabn** [comment]
Thanks for your attention, I'm looking forward to the update.

**Comment by BierOne** [comment]
Hi, thank you for your patience. I have uploaded the source code for NAC-ME in [here](https://github.com/BierOne/ood_coverage/tree/master/domainbed), which is tailored for generalization tasks. Hope you find it helpful!

**Comment by emanehabn** [comment]
Thank you so much; I really appreciate your commitment and support!
